#!bin/bash

curl  -s $TEGBZN_CONF_URL -o /home/nzbget/nzbget.conf && 
echo 'nzbget config loaded' || { echo 'ERROR: unable to get nzbget config' ; exit 1; }

curl  -s $RCONF_URL -o /home/.config/rclone/rclone.conf && 
echo 'rclone config loaded' || { echo 'ERROR: unable to get rclone config' ; exit 1; }

# Rewrites certain options in nzbget.conf:
sed -i \
    -e 's/^ControlPort=.*$/ControlPort='${PORT}'/' \
    -e 's/^ControlUsername=.*$/ControlUsername='${CTRL_USERNAME}'/' \
    -e 's/^ControlPassword=.*$/ControlPassword='${CTRL_PASS}'/' \
    -e 's/^MainDir=.*$/MainDir=\/home\/nzbget\/maindir\//' \
    -e 's/^Extensions=.*$/Extensions=rclone_pp.py/' \
    -e 's/^FormAuth=.*$/FormAuth=yes/' \
    /home/nzbget/nzbget.conf

./nzbget/nzbget -o ControlPort=$PORT -D

python3 ping.py
